spring.application.name=HotelBookingApplication

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/hotelbooking?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2
spring.datasource.username=Sq7d5GDkXs4Tuwc.root
spring.datasource.password=WpUtSNGpW5Yjx6qm
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# App Properties

auth.token.expirationInMils=3600000
auth.token.jwtSecret=36763979244226452948404D635166546A576D5A7134743777217A25432A462D

server.port=${PORT:8080}

razorpay.key.id=rzp_live_T76TroDSDb0mcZ
razorpay.key.secret=jxa3ZW4egrTrtXcQ7GxQlh3M